Additional code for V9>v10 module migration
FLPub/symbaroum5ecore pull request #49
Opened 2022-11-01 11:35 UTC by pwatson100

2022-11-02 15:16 UTC, trioderegion requested changes
Mostly just cleanup changes. One actual code change.

2022-11-02 15:16 UTC, trioderegion commented on css/symbaroum-dnd5e-mod.css
> +} */
Remove commented code (git remembers all)

2022-11-02 15:16 UTC, trioderegion commented on css/symbaroum-dnd5e-mod.css
> +} */
Remove commented code (git remembers all)

2022-11-02 15:16 UTC, trioderegion commented on css/symbaroum-dnd5e-mod.css
> +} */
Remove commented code (git remembers all)

2022-11-02 15:16 UTC, trioderegion commented on scripts/core.js
> +  Journal.registerSheet('SYB5E', SymbaroumWide, { label: game.i18n.localize('SYB5E.journal.widejournal.name'), makeDefault: false });
Move this registration to a 'register' function within 'SymbaroumWide', similar to the other registration functions.

2022-11-02 15:16 UTC, trioderegion commented on scripts/modules/journal.js
> +// }
Remove commented code (git remembers all)

2022-11-02 19:43 UTC, trioderegion commented on scripts/core.js
> +  Journal.registerSheet('SYB5E', SymbaroumWide, { label: game.i18n.localize('SYB5E.journal.widejournal.name'), makeDefault: false });
Resolved in update.

2022-11-03 03:54 UTC, trioderegion requested changes
Just the css commented lines remain.

2022-11-03 11:12 UTC, pwatson100 commented on css/symbaroum-dnd5e-mod.css
> +} */
Removed

2022-11-03 12:42 UTC, trioderegion approved these changes

2022-11-03 13:31 UTC, merged